DATA_BASE_DIR: "data/processed/"

DATA_TRAIN_RAW_DIRS: ["fish/raw/train"]
DATA_TRAIN_GT_DIRS: ["fish/gt/train"]

DATA_PRED_RAW_DIRS: ["fish/raw/test"]
DATA_PRED_GT_DIRS: ["fish/gt/test"]

DISTRIBUTION_MODE: "proportional"

MODEL: "probabilistic"
WEIGHT_MODE: "pixel"
MAIN_NET_DEPTH: 3
NUM_SUBNETS: 2
SUB_NET_DEPTH: 3
NUM_CLASSES: 1
IN_CHANNELS: 1
START_FILTS: 64
LEARNING_RATE: 0.0001
