EXTENDS_CONFIG: "config.yml"

DATA_BASE_DIR: "data/processed/mouse"

DATA_PRED_RAW_DIRS: ["gauss30/test"]
DATA_PRED_GT_DIRS: ["gt/test"]

PRED_NETWORK_PATH: "best.net"
PRED_OUTPUT_PATH: "prediction_gauss30"
OUTPUT_IMAGE_FORMATS: []
WRITE_SUBNETWORK_IMAGES: yes
WRITE_SUBNETWORK_PROBABILITIES: yes
WRITE_STD: yes
