DATA_BASE_DIR: "data/processed/"

DATA_TRAIN_RAW_DIRS: ["fish/avg16/train", "mouse/gauss30/train"]
DATA_TRAIN_GT_DIRS: ["fish/gt/train", "mouse/gt/train"]

DATA_PRED_RAW_DIRS: ["fish/avg16/test", "mouse/gauss30/test"]
DATA_PRED_GT_DIRS: ["fish/gt/test", "mouse/gt/test"]

DISTRIBUTION_MODE: "proportional"

MODEL: "q_learning"
EPSILON_START: 1.0
EPSILON_MIN: 0.1
EPSILON_DECAY: 0.996
#WEIGHT_MODE: "image"
MAIN_NET_DEPTH: 3
NUM_SUBNETS: 2
SUB_NET_DEPTH: 3
NUM_CLASSES: 1
IN_CHANNELS: 1
START_FILTS: 64
LEARNING_RATES:
    LEARNING_RATE_SUB_NETS: 0.0001
    LEARNING_RATE_MAIN_NET: 0.0001
UP_MODE: "transpose"
MERGE_MODE: "add"
DEVICE: "cuda:0"

EPOCHS: 2000
STEPS_PER_EPOCH: 5
VALIDATION_RATIO: 0.1
BATCH_SIZE: 24
AUGMENT_DATA: True
TRAIN_PATCH_SIZE: 100
PRED_PATCH_SIZE: 128
VIRTUAL_BATCH_SIZE: 20
OVERLAP: 48

TRAIN_NETWORK_PATH: "fused.net"
FREEZE_SUBNETS: True
WRITE_TENSORBOARD_DATA: yes
WRITE_EXAMPLE_IMAGE: no
PRED_NETWORK_PATH: "best.net"
PRED_OUTPUT_PATH: "prediction"
OUTPUT_IMAGE_FORMATS: ["tif"]
WRITE_SUBNETWORK_IMAGES: yes
WRITE_SUBNETWORK_WEIGHTS: yes
