DATA_BASE_DIR: "data/processed/"

DATA_TRAIN_RAW_DIRS: ["fish/cropped/avg16/train", "mouse/cropped/gauss30/train", "simsim/all_3_times/raw/train"]
DATA_TRAIN_GT_DIRS: ["fish/cropped/gt/train", "mouse/cropped/gt/train", "simsim/all_3_times/gt/train"]

DATA_PRED_RAW_DIRS: ["fish/cropped/avg16/test", "mouse/cropped/gauss30/test", "simsim/all/raw/test"]
DATA_PRED_GT_DIRS: ["fish/cropped/gt/test", "mouse/cropped/gt/test", "simsim/all/gt/test"]

DISTRIBUTION_MODE: "even"

MODEL: "baseline"
DEPTH: 3
NUM_CLASSES: 1
IN_CHANNELS: 1
START_FILTS: 64
LEARNING_RATE: 0.0001
UP_MODE: "transpose"
MERGE_MODE: "add"
DEVICE: "cuda:0"

EPOCHS: 1500
STEPS_PER_EPOCH: 5
VALIDATION_RATIO: 0.1
BATCH_SIZE: 20
AUGMENT_DATA: True
TRAIN_PATCH_SIZE: 100
PRED_PATCH_SIZE: 128
VIRTUAL_BATCH_SIZE: 20
OVERLAP: 48

#TRAIN_NETWORK_PATH: "best.net"
WRITE_TENSORBOARD_DATA: yes
WRITE_EXAMPLE_IMAGE: yes

PRED_NETWORK_PATH: "best.net"
PRED_OUTPUT_PATH: "prediction"
OUTPUT_IMAGE_FORMATS: ["tif"]
WRITE_SUBNETWORK_IMAGES: yes
WRITE_SUBNETWORK_WEIGHTS: yes
