EXTENDS_CONFIG: "config.yml"

DATA_BASE_DIR: "data/processed/"

DATA_PRED_RAW_DIRS: ["simsim/part1/raw/test", "simsim/part2/raw/test", "simsim/part3/raw/test"]
DATA_PRED_GT_DIRS: ["simsim/part1/gt/test", "simsim/part2/gt/test", "simsim/part3/gt/test"]

PRED_NETWORK_PATH: "best.net"
PRED_OUTPUT_PATH: "prediction_simsim"
OUTPUT_IMAGE_FORMATS: []
WRITE_SUBNETWORK_IMAGES: yes
WRITE_SUBNETWORK_PROBABILITIES: yes
WRITE_STD: yes
