EXTENDS_CONFIG: "config.yml"

DATA_BASE_DIR: "data/processed/fish"

DATA_PRED_RAW_DIRS: ["avg16/test"]
DATA_PRED_GT_DIRS: ["gt/test"]

PRED_NETWORK_PATH: "best.net"
PRED_OUTPUT_PATH: "prediction_fish"
OUTPUT_IMAGE_FORMATS: []
WRITE_SUBNETWORK_IMAGES: yes
WRITE_SUBNETWORK_WEIGHTS: yes
