DATA_BASE_DIR: "data/processed/fish/"

DATA_TRAIN_RAW_DIRS: ["raw/train"]
#DATA_TRAIN_GT_DIRS: ["gt/train"]

DATA_PRED_RAW_DIRS: ["raw/test"]
DATA_PRED_GT_DIRS: ["gt/test"]

DISTRIBUTION_MODE: "proportional"

MODEL: "baseline"
DEPTH: 3
NUM_CLASSES: 1
IN_CHANNELS: 1
START_FILTS: 64
LEARNING_RATES:
    LEARNING_RATE: 0.0001
UP_MODE: "transpose"
MERGE_MODE: "add"
DEVICE: "cuda:0"

EPOCHS: 1000
STEPS_PER_EPOCH: 5
VALIDATION_RATIO: 0.1
BATCH_SIZE: 24
AUGMENT_DATA: True
# To achieve higher depth the patch size needs to be dividible by 2 6 times
TRAIN_PATCH_SIZE: 128
PRED_PATCH_SIZE: 128
VIRTUAL_BATCH_SIZE: 20
OVERLAP: 32

#TRAIN_NETWORK_PATH: "best.net"
WRITE_TENSORBOARD_DATA: yes
WRITE_EXAMPLE_IMAGE: no
PRED_NETWORK_PATH: "best.net"
PRED_OUTPUT_PATH: "prediction"
OUTPUT_IMAGE_FORMATS: ["tif"]
WRITE_SUBNETWORK_IMAGES: yes
WRITE_SUBNETWORK_WEIGHTS: yes
